# Generated by Django 4.1.6 on 2023-04-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telenovelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='movie/images/')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
